num_1 = int(input("Enter the first number: "))
num_2 = int(input("Enter the second number: "))
print("addition: ",num_1+num_2)
print("subtraction: ",num_1-num_2)
print("multiplication: ",num_1*num_2)
print("devision: ",num_1/num_2)
